//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shauli.CountryWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.webserviceX.NET", ConfigurationName="CountryWebService.countrySoap")]
    public interface countrySoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetCountryByCountryCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetCountryByCountryCode(string CountryCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetCountryByCountryCode", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetCountryByCountryCodeAsync(string CountryCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetISD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetISD(string CountryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetISD", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetISDAsync(string CountryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetCountries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetCountries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetCountries", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetCountriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetCurrencyCodeByCurrencyName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetCurrencyCodeByCurrencyName(string CurrencyName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetCurrencyCodeByCurrencyName", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetCurrencyCodeByCurrencyNameAsync(string CurrencyName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetISOCountryCodeByCountyName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetISOCountryCodeByCountyName(string CountryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetISOCountryCodeByCountyName", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetISOCountryCodeByCountyNameAsync(string CountryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetCurrencyCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetCurrencyCode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetCurrencyCode", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetCurrencyCodeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetCountryByCurrencyCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetCountryByCurrencyCode(string CurrencyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetCountryByCurrencyCode", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetCountryByCurrencyCodeAsync(string CurrencyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetCurrencies", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetCurrencies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetCurrencies", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetCurrenciesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetCurrencyByCountry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetCurrencyByCountry(string CountryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetCurrencyByCountry", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetCurrencyByCountryAsync(string CountryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetGMTbyCountry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetGMTbyCountry(string CountryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetGMTbyCountry", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetGMTbyCountryAsync(string CountryName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface countrySoapChannel : Shauli.CountryWebService.countrySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class countrySoapClient : System.ServiceModel.ClientBase<Shauli.CountryWebService.countrySoap>, Shauli.CountryWebService.countrySoap {
        
        public countrySoapClient() {
        }
        
        public countrySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public countrySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public countrySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public countrySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetCountryByCountryCode(string CountryCode) {
            return base.Channel.GetCountryByCountryCode(CountryCode);
        }
        
        public System.Threading.Tasks.Task<string> GetCountryByCountryCodeAsync(string CountryCode) {
            return base.Channel.GetCountryByCountryCodeAsync(CountryCode);
        }
        
        public string GetISD(string CountryName) {
            return base.Channel.GetISD(CountryName);
        }
        
        public System.Threading.Tasks.Task<string> GetISDAsync(string CountryName) {
            return base.Channel.GetISDAsync(CountryName);
        }
        
        public string GetCountries() {
            return base.Channel.GetCountries();
        }
        
        public System.Threading.Tasks.Task<string> GetCountriesAsync() {
            return base.Channel.GetCountriesAsync();
        }
        
        public string GetCurrencyCodeByCurrencyName(string CurrencyName) {
            return base.Channel.GetCurrencyCodeByCurrencyName(CurrencyName);
        }
        
        public System.Threading.Tasks.Task<string> GetCurrencyCodeByCurrencyNameAsync(string CurrencyName) {
            return base.Channel.GetCurrencyCodeByCurrencyNameAsync(CurrencyName);
        }
        
        public string GetISOCountryCodeByCountyName(string CountryName) {
            return base.Channel.GetISOCountryCodeByCountyName(CountryName);
        }
        
        public System.Threading.Tasks.Task<string> GetISOCountryCodeByCountyNameAsync(string CountryName) {
            return base.Channel.GetISOCountryCodeByCountyNameAsync(CountryName);
        }
        
        public string GetCurrencyCode() {
            return base.Channel.GetCurrencyCode();
        }
        
        public System.Threading.Tasks.Task<string> GetCurrencyCodeAsync() {
            return base.Channel.GetCurrencyCodeAsync();
        }
        
        public string GetCountryByCurrencyCode(string CurrencyCode) {
            return base.Channel.GetCountryByCurrencyCode(CurrencyCode);
        }
        
        public System.Threading.Tasks.Task<string> GetCountryByCurrencyCodeAsync(string CurrencyCode) {
            return base.Channel.GetCountryByCurrencyCodeAsync(CurrencyCode);
        }
        
        public string GetCurrencies() {
            return base.Channel.GetCurrencies();
        }
        
        public System.Threading.Tasks.Task<string> GetCurrenciesAsync() {
            return base.Channel.GetCurrenciesAsync();
        }
        
        public string GetCurrencyByCountry(string CountryName) {
            return base.Channel.GetCurrencyByCountry(CountryName);
        }
        
        public System.Threading.Tasks.Task<string> GetCurrencyByCountryAsync(string CountryName) {
            return base.Channel.GetCurrencyByCountryAsync(CountryName);
        }
        
        public string GetGMTbyCountry(string CountryName) {
            return base.Channel.GetGMTbyCountry(CountryName);
        }
        
        public System.Threading.Tasks.Task<string> GetGMTbyCountryAsync(string CountryName) {
            return base.Channel.GetGMTbyCountryAsync(CountryName);
        }
    }
}
